### ISSUE TITLE
seg fault when using https on request.bin

### ISSUE THREAD

**Issue by christopher5106** [daurnimator/lua-http#39]
This example which works with cURL : 

```lua
  local uri = "https://requestb.in/XXXXXX"
  local req_body = "ljmsjkfdm"
  local req_timeout = 10

  local request = require "http.request"

  local req = request.new_from_uri(uri)
  if req_body then
  	req.headers:upsert(":method", "POST")
  	req:set_body(req_body)
  end

  print("# REQUEST")
  print("## HEADERS")
  for k, v in req.headers:each() do
  	print(k, v)
  end
  print()
  if req.body then
  	print("## BODY")
  	print(req.body)
  	print()
  end

  print("# RESPONSE")
  local headers, stream = req:go(req_timeout)
```

**Comment by daurnimator** [comment]
I'm not getting a segfault here.
Though I did get an error: "lua: ./http/h2_stream.lua:221: bad argument #2 to 'spack' (number has no integer representation)", which I've now fixed.

What version(s) of lua-http (give me the commit#) and cqueues do you have installed?

**Comment by daurnimator** [comment]
@christopher5106?

**Comment by christopher5106** [comment]
The example I gave you still does not work on my Mac OS.
It occurs when I use the HTTPS instead of the HTTP in the request bin url.
I think on Ubuntu it works (on Ubuntu  it is ok if I remember well)

**Comment by daurnimator** [comment]
You're not giving me much to work with here. Does it replicate every time? Was it an actual seg fault? If so, can you give me a crash dump?

> The example I gave you still does not work on my Mac OS.

My first guess there is mismatched openssl versions. Which headers did you compile luaossl against? Which library did you link against?

**Comment by christopher5106** [comment]
Sorry for delay, I will give you more tests on Mac OS soon.

On Linux Ubuntu, it works, install with 

```
luarocks install --server=http://luarocks.org/dev http
```

did not work at first time. I add to specify paths. In case : 

```
luarocks install luaossl CRYPTO_LIBDIR=/usr/lib/x86_64-linux-gnu  CRYPTO_INCDIR=/usr/include OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu OPENSSL_INCDIR=/usr/include
sudo apt-get install m4
luarocks install cqueues CRYPTO_LIBDIR=/usr/lib/x86_64-linux-gnu  CRYPTO_INCDIR=/usr/include OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu OPENSSL_INCDIR=/usr/include
```

**Comment by daurnimator** [comment]
> I add to specify paths. In case :
> ```
> luarocks install luaossl CRYPTO_LIBDIR=/usr/lib/x86_64-linux-gnu  CRYPTO_INCDIR=/usr/include OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu OPENSSL_INCDIR=/usr/include
> ```

That suprises me. `/usr/include` should never need to be added (it's the default).
Likewise I'm confused why `/usr/lib/x86_64-linux-gnu` would not be searched by default. It sounds like you might have a misconfigured luarocks installation.

> sudo apt-get install m4

Yes you do need m4 to compile cqueues. Most people have it installed already... I'm not sure if build instructions for cqueues should be present in lua-http though...

**Comment by mpeterv** [comment]
@christopher5106 what's your luarocks version? It should look in `/usr/lib/x86_64-linux-gnu` starting from 2.1.1.

**Comment by christopher5106** [comment]
2.3.0

I will tell you a bit more tomorrow when I'm on Mac OS as well. 

On Ubuntu it works if the install works. This is true it could be a bit more "convenient" to install.

**Comment by mpeterv** [comment]
And what output does luarocks produce on Ubuntu when you don't explicitly provide paths?

**Comment by mpeterv** [comment]
Also, what output does `gcc -print-multiarch` produce.

**Comment by christopher5106** [comment]
It outputs x86_64-linux-gnu

It breaks and says to add the paths. For example, in luaossl, it says to add CRYPTO_DIR, then CRYPTO_INCDIR, but still does not work, so I use CRYPTO_LIBDIR instead of CRYPTO_DIR that would override...

**Comment by mpeterv** [comment]
Please post exact output

**Comment by christopher5106** [comment]
luarocks install luaossl
Installing https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/luaossl-20151221-1.src.rock...
Using https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/luaossl-20151221-1.src.rock... switching to 'build' mode

Error: Could not find library file for CRYPTO
  No file libcrypto.a in /usr/lib
  No file libcrypto.so in /usr/lib
  No file matching libcrypto.so.* in /usr/lib
You may have to install CRYPTO in your system and/or pass CRYPTO_DIR or CRYPTO_LIBDIR to the luarocks command.
Example: luarocks install luaossl CRYPTO_DIR=/usr/local

**Comment by mpeterv** [comment]
What are the contents of your site config? With lua version `5.x` and luarocks in `<prefix>` it's most likely `<prefix>/share/lua/5.x/luarocks/site_config.lua`.

**Comment by christopher5106** [comment]
cat install/share/lua/5.1/luarocks/site_config.lua 
local site_config = {}

site_config.LUAROCKS_PREFIX=[[/home/christopher/torch/install/]]
site_config.LUA_INCDIR=[[/home/christopher/torch/install/include]]
site_config.LUA_LIBDIR=[[/home/christopher/torch/install/lib]]
site_config.LUA_BINDIR=[[/home/christopher/torch/install/bin]]
site_config.LUA_INTERPRETER = [[luajit]]
site_config.LUAROCKS_SYSCONFDIR=[[/home/christopher/torch/install/etc/luarocks]]
site_config.LUAROCKS_ROCKS_TREE=[[/home/christopher/torch/install/]]
site_config.LUAROCKS_ROCKS_SUBDIR=[[lib/luarocks/rocks]]
site_config.LUA_DIR_SET = true
site_config.LUAROCKS_UNAME_S=[[Linux]]
site_config.LUAROCKS_UNAME_M=[[x86_64]]
site_config.LUAROCKS_DOWNLOADER=[[wget]]
site_config.LUAROCKS_MD5CHECKER=[[md5sum]]

return site_config

**Comment by mpeterv** [comment]
Then this is an issue with torch/distro: their [bundled config](https://github.com/torch/luajit-rocks/blob/411f4b9d9c4be176d4aab965ebfce50911583e14/luarocks/src/luarocks/site_config.lua.in) is incorrect and should include lines

```lua
site_config.LUAROCKS_EXTERNAL_DEPS_SUBDIRS={ bin="bin", lib={ "lib", [[lib/x86_64-linux-gnu]] }, include="include" }
site_config.LUAROCKS_RUNTIME_EXTERNAL_DEPS_SUBDIRS={ bin="bin", lib={ "lib", [[lib/x86_64-linux-gnu]] }, include="include" }
```

on x64 Linux.

**Comment by daurnimator** [comment]
@christopher5106 so sounds like that's the source of your issue on ubuntu (thankyou @mpeterv!)
Please let me know more about your OSX process.

**Comment by daurnimator** [comment]
@christopher5106 ping?

**Comment by daurnimator** [comment]
Closing due to lack of reply. You may want to check out https://github.com/wahern/cqueues/wiki/Installation-on-OSX for cqueues installation hints.

**Comment by d9k** [comment]
(sorry for invalid reference, deleted comment there, reference is still present)
